[build]
  base = "deniscode/deniscode"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# SPA fallback (Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache forte para assets gerados pelo Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
